name: Basic CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'chart/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GAR
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.GCP_REGION }}-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GAR_JSON_KEY }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/apps/hello-world:${{ github.sha }}
          ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/apps/hello-world:latest

    - name: Update Helm values file
      run: |
        sed -i "s/tag:.*/tag: '${{ github.sha }}'/g" chart/values.yaml

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add chart/values.yaml
        git commit -m "Update Helm values file with latest tag [skip ci]"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
